version: '3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    volumes:
      - C:/Users/lehch/Docker_Volumes/mysqldb:/var/lib/mysql


    networks:
      - mediscreen-app

  mediscreen:
    depends_on:
      - mysqldb
    image: mediscreen-patient:latest
    container_name: mediscreen-patient
    build:
      context: ./Patient
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "8081:8081"

    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/mediscreen?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
      volumes:
        -/my/project/dir:/app
      #stdin_open: true
      #tty: true

    networks:
      - mediscreen-app

  mongodb: