version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/lehch/Docker_Volumes/mysqldb:/var/lib/mysql
    networks:
      - mediscreen-app

  patient:
    depends_on:
      - mysqldb
    image: patient:latest
    container_name: patient
    build:
      context: ./Patient
      dockerfile: Dockerfile
    restart: on-failure
    env_file: ./.env
    ports:
      - "8081:8081"

    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/mediscreen?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
      volumes:
        -/my/project/dir:/app

    - "note.serviceUrl=http://note:8082"

    networks:
      - mediscreen-app

  mongodb:
    image: mongo:4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/lehch/Docker_Volumes/mongodb:/data/db
    networks:
      - mediscreen-app

  note:
    depends_on:
      - mongodb
    image: note:latest
    container_name: note
    ports:
      - "8082:8082"
    environment:
          - "spring_data_mongodb_host=mongodb"
          - "spring.data.mongodb.database=mediscreen"
          - "patient.serviceUrl=http://patient:8081"
          - "note.serviceUrl=http://note:8082"
    networks:
          - mediscreen-app


  diagnostic:
    image: diagnostic:latest
    container_name: diagnostic
    ports:
      - "8083:8083"
    environment:
        - "patient.serviceUrl=http://patient:8081"
        - "note.serviceUrl=http://note:8082"
    networks:
        - mediscreen-app


  mediscreen:
    image: mediscreen:latest
    container_name: Mediscreen
    ports:
      - "8080:8080"
    environment:
      - "diagnostic.serviceUrl=http://diagnostic:8083"
      - "patient.serviceUrl=http://patient:8081"
      - "note.serviceUrl=http://note:8082"
    networks:
      - mediscreen-app




networks:
  mediscreen-app:
    driver: bridge

volumes:
  mysqldb:
  mongodb:
